# Generated by Django 6.0.5 on 2026-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('failures', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'ip_address')},
            },
        ),
    ]
