# Generated by Django 6.0.5 on 2026-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_chapterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
