# Generated by Django 6.0.5 on 2026-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_chapter_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
