# Generated by Django 6.0.5 on 2026-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_category_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='topic_level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Level 2 (##)'), (3, 'Level 3 (###)')], default=2),
        ),
    ]
